### ISSUE TITLE
Can kajiwoto-clientsdk-golang call kajiwoto through the api for dialogue?

### ISSUE THREAD

**Issue by dragonorant** [RuntimeRacer/kajiwoto-clientsdk-golang#1]
Can kajiwoto-clientsdk-golang call kajiwoto through the api for dialogue?

**Comment by RuntimeRacer** [comment]
Hello, technically yes, using the WebSocket client, but I didn't have the time yet to add an End-To-End Example, also for proper testing. You could however take a look at this test here: https://github.com/RuntimeRacer/kajiwoto-clientsdk-golang/blob/main/websocket/client_test.go#L155

There is also a commented out secton for a Chat Activity Event of type `petMessage`, which you'd require to listen to for handling Kaji messages.

To send and receive Kaji Messages, you'll need to be subscribed and and have entered the chat. Also you'll have to use both
https://github.com/RuntimeRacer/kajiwoto-clientsdk-golang/blob/main/websocket/types.go#L317 
and potentially 
https://github.com/RuntimeRacer/kajiwoto-clientsdk-golang/blob/main/websocket/types.go#L349 
to send a Message to a Kaji.

But that's not fully tested yet and you might run into issues. I'll be working on this soon, maybe even today; but feel free to play around with it

**Comment by dragonorant** [comment]
> 你好，技术上是的，使用 WebSocket 客户端，但我还没有时间添加端到端示例，也用于适当的测试。但是，您可以在此处查看此测试： https: [//github.com/RuntimeRacer/kajiwoto-clientsdk-golang/blob/main/websocket/client_test.go#L155](https://github.com/RuntimeRacer/kajiwoto-clientsdk-golang/blob/main/websocket/client_test.go#L155)
> 
> 还有一个类型为 Chat Activity Event 的注释掉的部分`petMessage`，您需要收听它来处理 Kaji 消息。
> 
> 要发送和接收 Kaji 消息，您需要订阅并进入聊天。此外，您还必须同时使用 https://github.com/RuntimeRacer/kajiwoto-clientsdk-golang/blob/main/websocket/types.go#L317 和潜在的 [https://github.com/RuntimeRacer/kajiwoto-clientsdk -golang/blob/main/websocket/types.go#L349](https://github.com/RuntimeRacer/kajiwoto-clientsdk-golang/blob/main/websocket/types.go#L349) 向 Kaji 发送消息。
> 
> 但这尚未经过全面测试，您可能会遇到问题。我很快就会着手解决这个问题，甚至可能是今天；但请随意使用它

Ok, thank you for your answer.
But I am not developing in go language, but in java, so I may need to modify it.

**Comment by RuntimeRacer** [comment]
Feel free to fork and / or make your own java SDK for it to share with the community as well. Just be aware that this repo is not an "official" one; the backend APIs might change without notice, and also I won't always be able to be on top of all changes. However feel free to also reach out to Saeho (Creator & Dev of Kajiwoto) via Discord in case you have any detailed questions regarding Backend mechanics.

**Comment by dragonorant** [comment]
Ok, thank you, but I have contacted Saeho. Kwaj is not allowed to be used in business, but I originally planned to access it in our game.
